Mon Dec  9 16:58:58 EST 2024
c1106a-s35.ufhpc
/blue/bsc4452/Marisa1988/PruebaAlphaFold
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (335) bind mounts
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Read-only file system
I1209 16:59:05.555336 22776941745984 templates.py:857] Using precomputed obsolete pdbs /data/reference/alphafold/2.3.2/pdb_mmcif/obsolete.dat.
I1209 16:59:06.193650 22776941745984 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1209 16:59:06.965747 22776941745984 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I1209 16:59:06.966107 22776941745984 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I1209 16:59:06.966175 22776941745984 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
I1209 16:59:12.431663 22776941745984 run_alphafold.py:424] Have 5 models: ['model_1_pred_0', 'model_2_pred_0', 'model_3_pred_0', 'model_4_pred_0', 'model_5_pred_0']
I1209 16:59:12.431904 22776941745984 run_alphafold.py:438] Using random seed 1549967697219087631 for the data pipeline
I1209 16:59:12.432086 22776941745984 run_alphafold.py:185] Predicting uniprotkb_2024_12_04.fasta
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 443, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 189, in predict_structure
    os.makedirs(output_dir)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '~'
Mon Dec  9 16:59:17 EST 2024
